import Head from 'next/head';
import Image from 'next/image';
import { Inter } from '@next/font/google';
import styles from '@/styles/Home.module.css';

import Churches from '@/components/Churches/Churches';

export const getStaticProps = async () => {
  const res = await fetch('http://localhost:3000/api/churches');
  const churches = await res.json();

  return {
    props: {
      churches,
    },
  };
};


export default function Home({ churches }: { churches: any }) {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name='description' content='Generated by create next app' />
        <meta name='viewport' content='width=device-width, initial-scale=1' />
        <link rel='icon' href='/favicon.ico' />
      </Head>
      <main>
        <h1>Church Localizer</h1>
        <Churches churches={churches} />
      </main>
    </>
  );
}
