export const datosIglesias = [
  {
    id: 1,
    name: 'Iglesia de la Comunidad de Madrid',
    address: 'Calle de la Iglesia, 1, 28001 Madrid',
    schedule: 'Lunes a sabados de 9:00 a 14:00',
    image: 'https://live.staticflickr.com/867/39251370590_9639779b29_b.jpg',
    capacity: 100,
    dressProtocol: 'Vestimenta formal',
    healthProtocol: 'Uso de mascarilla obligatorio',
    baptism: true,
    firstCommunion: true,
    confirmation: true,
    wedding: true,
    priest: 'P. Juan',
    phone: 123456789,
  },
  {
    id: 2,
    name: 'Iglesia 2',
    address: 'Calle de la Iglesia, 1, 28001 Madrid',
    schedule: 'Lunes a sabados de 9:00 a 14:00',
    image: 'https://th.bing.com/th/id/OIP.wWpsUPhhRyBqsCAl5vT5HQHaJ4?pid=ImgDet&rs=1',
    capacity: 100,
    dressProtocol: 'Vestimenta formal',
    healthProtocol: 'Uso de mascarilla obligatorio',
    baptism: false,
    firstCommunion: false,
    confirmation: false,
    wedding: false,
    priest: 'P. Portilo',
    phone: 123456789,
  },

  {
    id: 3,
    name: 'Iglesia 3',
    address: 'Calle de la Iglesia, 1, 28001 Madrid',
    schedule: 'Lunes a sabados de 9:00 a 14:00',
    image: 'https://th.bing.com/th/id/OIP.wWpsUPhhRyBqsCAl5vT5HQHaJ4?pid=ImgDet&rs=1',
    capacity: 100,
    dressProtocol: 'Vestimenta formal',
    healthProtocol: 'Uso de mascarilla obligatorio',
    baptism: false,
    firstCommunion: false,
    confirmation: false,
    wedding: false,
    priest: 'P. Portilo',
    phone: 123456789,
  },

  {
    id: 4,
    name: 'Iglesia 4',
    address: 'Calle de la Iglesia, 1, 28001 Madrid',
    schedule: 'Lunes a sabados de 9:00 a 14:00',
    image: 'https://th.bing.com/th/id/OIP.wWpsUPhhRyBqsCAl5vT5HQHaJ4?pid=ImgDet&rs=1',
    capacity: 100,
    dressProtocol: 'Vestimenta formal',
    healthProtocol: 'Uso de mascarilla obligatorio',
    baptism: false,
    firstCommunion: false,
    confirmation: false,
    wedding: false,
    priest: 'P. Portilo',
    phone: 123456789,
  },

  {
    id: 5,
    name: 'Iglesia 5',
    address: 'Calle de la Iglesia, 1, 28001 Madrid',
    schedule: 'Lunes a sabados de 9:00 a 14:00',
    image: 'https://th.bing.com/th/id/OIP.wWpsUPhhRyBqsCAl5vT5HQHaJ4?pid=ImgDet&rs=1',
    capacity: 100,
    dressProtocol: 'Vestimenta formal',
    healthProtocol: 'Uso de mascarilla obligatorio',
    baptism: false,
    firstCommunion: false,
    confirmation: false,
    wedding: false,
    priest: 'P. Portilo',
    phone: 123456789,
  },
];
